function Hd = fir_lpf_kaiser_window_Fpass9MHz_Fstop11_85_Fs61_44
%FIR_LPF_KAISER_WINDOW_FPASS9MHZ_FSTOP11.85_FS61_44 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 21-Jun-2015 12:02:48

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in MHz.
Fs = 61.44;  % Sampling Frequency

Fpass = 9;                % Passband Frequency
Fstop = 11.85;            % Stopband Frequency
Dpass = 0.057501127785;   % Passband Ripple
Dstop = 0.0031622776602;  % Stopband Attenuation
flag  = 'noscale';        % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
%Hd = dfilt.dffir(b);
Hd.Numerator    = b;
Hd.Denominator  = 1;

% [EOF]
